[package]
name = "terraswap-token"
version = "0.0.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Backward compatible implementation of a CosmWasm-20 compliant token"
license = "MIT"
repository = "https://github.com/terraswap/terraswap"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw0 = { git = "https://github.com/CosmWasm/cosmwasm-plus", branch = "v0.7.x" } 
cw2 = { git = "https://github.com/CosmWasm/cosmwasm-plus", branch = "v0.7.x" } 
cw20 = { git = "https://github.com/CosmWasm/cosmwasm-plus", branch = "v0.7.x" } 
cw-storage-plus  = { git = "https://github.com/CosmWasm/cosmwasm-plus", branch = "v0.7.x", features = ["iterator"] } 
cosmwasm-std = { version = "0.15.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.15.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }

[dev-dependencies]
# we only need to enable this if we use integration tests
cosmwasm-schema = { version = "0.15.0" }
